version: '3.4'
services:
  linuxgsm-minecraft:
    image: gameservermanagers/gameserver:mc
    container_name: minecraft-server
    ports:
      - "${GAMESERVER_IP}:25565:25565/tcp"
    volumes:
      - ${DATA_PATH}/minecraft:/data
    restart: unless-stopped
  
  linuxgsm-factorio:
    image: gameservermanagers/gameserver:fctr
    # image: ghcr.io/gameservermanagers/gameserver:sf
    container_name: factorio
    restart: unless-stopped
    volumes:
      - factorio-volume:/data
    network_mode: host
volumes:
  factorio-volume: